# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313fc44aff80766e98d346e7305d706003bc179c45f55daf787aae1bc86d4adbb3f600858ba10f4a1f436f8ff38d6e66a6c5971c66ecde1f70f60151a7bafe57

test:
  secret_key_base: d0bfa8ce5eaeb56033b961bad548d348241cdbc6a7b7b9287d23ee39357328d56aceb8dc6e86dae3014a955eec6379257699426bcd71be558db40deeef7179cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
